### ISSUE TITLE
README enhancements

### ISSUE THREAD

**Issue by mjrdnk** [mjrdnk/captioner#1]
Readme enhancements needed.

**Comment by ghost** [comment]
I'd love to take this on, I am trying to introduce myself to making open source contributions for a 20 minute talk to my fellow cohorts. Would you provide any specifics that might be missed from watching the video, investigating the docs, and closed issues? I'm still pretty green.

**Comment by ghost** [comment]
See PR #3 
I hope that you can use some of this.

**Comment by ghost** [comment]
@xorz57 I feel that inclusion of the original contributors is important but your markdown is far superior would you be interesting in collaborating on this to see us both make the final cut? First Hacktober PR sent either way woot. Is that what led you here aswell?

**Comment by ghost** [comment]
I believe we could merge my PR first and then work on your PR together. start your pull request too!
